language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  - sudo add-apt-repository -y ppa:marutter/rrutter # R
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq r-base r-base-dev  # R
  - sudo apt-get install -qq lyx texlive  # pdflatex, used by knitr
  - sudo Rscript install_r_packages.R  # Rcpp

script: 
  # C++
  - ./build_cpp.sh
  # R wants all non-R files gone...
  - ./clean.sh
  - rm .gitignore
  - rm src/.gitignore
  - rm .travis.yml
  - rm -rf .git
  - rm -rf ..Rcheck
  # Now R is ready to go
  - R CMD check .

after_success:
  - cat /home/travis/build/richelbilderbeek/travis_qmake_gcc_cpp11_rcpp/..Rcheck/00check.log

after_failure:
  - cat /home/travis/build/richelbilderbeek/travis_qmake_gcc_cpp11_rcpp/..Rcheck/00check.log